### ISSUE TITLE
midterm-jpark.py is ready

### ISSUE THREAD

**Issue by jttreichel** [madisoncollege-it-programs/python-scripting-jttreichel#11]

**Comment by cethenmc** [comment]
Wow!  So very close to bringing it home.  You made this more complicated than it had to be with your tuples, but you still almost made it work your way.  If you had just added .replace("\\n","") to the o in your print line, you would have had it (1 pt).  However, I still am taking off a point for the lack of well labeled variables (1 pt).  Make your variable names descriptive enough so I know you obviously kNice effort.  I enjoy seeing what you did.  The first thing I observed was failed logins.  Instead of printing the magic word clause with a counter on the first two failures you returned directly to offer a new attempt (2 pts).  After the second login failure, entering the correct username and password does not render successful entry (1 pt).   When prompting the user you were to print the extraction of the keys of the command_database dictionary, where as you hardcoded them (2 pts).  Similary, in lines 25 through 33 you should be pulling from the input to pull the correct value from the dictionary and you could consolidate on one if the three separate values being compared (2 pts).  Score 26/33.now what things are.  32/34.
