### ISSUE TITLE
Changes made to week 11 lab

### ISSUE THREAD

**Issue by jttreichel** [madisoncollege-it-programs/python-scripting-jttreichel#20]

**Comment by jttreichel** [comment]
I made some more changes to the script to match the screenshots as best i could.
Thanks

**Comment by cethenmc** [comment]
Thanks for giving another shot.  I believe it needed more of an effort than you were able to give time to it.  Unfortunately, this is the output for the list I received.  

![image](https://user-images.githubusercontent.com/112707666/208184435-0d79eab0-225b-4dbf-90bf-0f7f6c29a443.png)

Hopefully, the picture above demonstrates clearly to you what you had done incorrectly with the list.  It would have been nice if you cleaned up the help menu items, I pointed out, as well.  But the source of the bigger problem is the way your list is printing out.

As a result, I have to keep the score at a 7 out of 8, and your semester grade at 91.46%, an 'AB'.

You need this to turn out an 8 out of 8 to get above 91.5% and gain an 'A'.  I assume you probably did not have the time to make a greater effort on this last night.

**Please let me know _today_ if you would appreciate one last chance to perfect this assignment and earn the 'A' over the 'AB'.**  If you believe you have the time and desire to get the point, please just reply today.  For some, the grade does not matter because they are just taking a course for work or something, and I am completely fine with that, as well.

**If you do, then please let me know if you would have time to perfect it tonight or tomorrow.  I would give an extension for just this lab.**

Thanks.

Chris

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208700000-34c9d1dd-c0c1-4692-9e70-941e0afc77dd.png)

Class grade of AB this semester.  Nice work!
