### ISSUE TITLE
Flow Control Lab ready for grading

### ISSUE THREAD

**Issue by jttreichel** [madisoncollege-it-programs/python-scripting-jttreichel#8]

**Comment by cethenmc** [comment]
Requirements met.  It would have been nice had you also done something if someone chose anything other than door #1, 2, or 3, like 20, 0, 4, 25, 34, or anything else.  However, you did as the assignment requested.  Full credit.

**Comment by cethenmc** [comment]
Hi, Jacob.  Really nice work.  You made it more complex than it needed to be, but in doing all of that extra work you produced cleaner results.  There are two parts that I would like you to fix.  

Number 5 is really looking you to add two new mappings to the already created dictionary, after steps 2-4 occur.

Numbers 6 and 7 should be searching for "server2.testlab.com" and "server10.testlab.com," not just server2 and server 10.

I can except the way you did numbers 2 through 4, but in reality, we were really just looking for everyone to do keys(), values(), and items() on the dictionary.  Because of the way you chose to create the dictionary, you were forced to do them with your loop.  Nice work on this.

If you want, you could have literally started this way:
dictAddresses = ("server1.testlab.com" : "192.168.1.10", "server2.testlab.com" : "192.168.1.11", ...}

If you want to try it that way, too, feel free.  You may find yourself flying through.  **I recorded 5 of 8 for now, and will watch for your reply to this Issue Ticket after you resubmit.  If you don't want to resubmit, then please reply to this same Issue ticket.**
